### ISSUE TITLE
setting style left and top without unit px does not work with <!doctype html>

### ISSUE THREAD

**Issue by paradite** [DKirwan/calendar-heatmap#10]
Currently it is setting the styles without unit, it fails on certain browsers with the `<!doctype html>` tag.

See http://stackoverflow.com/questions/11274904/fallback-for-css-attributes-without-unit

More specifically: http://stackoverflow.com/questions/11274904/fallback-for-css-attributes-without-unit#comment14828170_11275156

Below is the fixed code, I also submitted a PR.

```
tooltip = d3.select('body')
              .append('div')
              .attr('class', 'day-cell-tooltip')
              .html(tooltipHTMLForDate(d))
              .style('left', function() {
                return Math.floor(i / 7) * SQUARE_LENGTH + 'px'; })
              .style('top', function() {
                return d.getDay() * (SQUARE_LENGTH + SQUARE_PADDING) + MONTH_LABEL_PADDING * 3 + 'px'; });
```

**Comment by DKirwan** [comment]
Thanks for this. I'll merge your PR and set to fixed!

**Comment by DKirwan** [comment]
#12
