### ISSUE TITLE
svg size can be wrongly calculated due to box-sizing

### ISSUE THREAD

**Issue by paradite** [DKirwan/calendar-heatmap#12]
currently the svg element does not specify `box-sizing` style, this works fine for the default `content-box` value, however, with frameworks like `bootstrap`, its default is set to `* { box-sizing: border-box; }`, which

> makes it so padding does not affect the final computed width of an element

The issue can be solved by enforcing the correct css `box-sizing` style to the svg element: 
```
.calendar-heatmap {
  box-sizing: initial;
}
```
See http://getbootstrap.com/getting-started/#third-box-sizing

**Comment by TheFive** [comment]
+1 and a simple change in the css

**Comment by DKirwan** [comment]
Good catch, @paradite. I'll fix this and release an update

**Comment by DKirwan** [comment]
Fixed in Version 0.4.1 pushed just now
