### ISSUE TITLE
Tooltip position taking 'body' instead of calendar selector

### ISSUE THREAD

**Issue by andresgcarmona** [DKirwan/calendar-heatmap#13]
In line 116 `tooltip = d3.select('body')` causes the tooltip to appear positioned relative to the document body instead of the calendar selector. I changed it to `tooltip = d3.select(chart.selector())` to fix the problem.

**Comment by DKirwan** [comment]
Good catch, @andresgcarmona. I'll hotfix this

**Comment by wataruoguchi** [comment]
Hey @DKirwan, I sent the pull request regarding this. Please merge it

**Comment by wataruoguchi** [comment]
thx for merging!
