### ISSUE TITLE
Week start day

### ISSUE THREAD

**Issue by joan16v** [DKirwan/calendar-heatmap#15]
I have a question or a petition... is possible to change the week start day to Monday?

**Comment by DKirwan** [comment]
That's a great question! At the moment we don't support this but I can completely see that use case. I won't be able to get to it this week but I can take a look. If you want to submit a pull request I'd be happy to work with you on it too.

**Comment by joan16v** [comment]
Excellent! I'll send a PR then asap :)

**Comment by DKirwan** [comment]
Thanks so much for the PR! I commented on it and I'll merge it once that's addressed :)
