### ISSUE TITLE
Import into a ng2 component

### ISSUE THREAD

**Issue by poulzinho** [DKirwan/calendar-heatmap#23]
Hi DKirwan,

My development team at [TUM](https://wwwmatthes.in.tum.de/pages/t5ma0jrv6q7k/sebis-Public-Website-Home) is in love with you Calendar-Heatmap. We are using it in a ng2 component with webpack.

The way it is done for the moment is:
- Napa for installing the repo in 'node-modules', and from the component:
`import * as CalendarHeatmap from '../../../node_modules/calendar-heatmap/src/calendar-heatmap.js'
`

This setup is working right now with a small modification in you calendar-heatmap.js
`import * as moment from 'moment';`
`module.exports = calendarHeatmap;`

We know that it's tricky but we really want to use your tool ;)

Is in your plans to modularize the calendar-heatmap and make it available at npm?

Regards,
Poulzinho

**Comment by DKirwan** [comment]
Hey Poulzinho,

That's awesome to hear! I'm an angular developer (1.x) and was interested in learning more about angular 2. I'd be happy to work on this and make it available via npm.

I'm pretty busy this week and next, but after that I'd love to take this on.

Great to hear you're using the chart!

Darragh

**Comment by DKirwan** [comment]
Poulzinho,

Just a quick update: I haven't got around to looking at this yet, and it will be next month before I have the capacity to take it on.

**Comment by poulzinho** [comment]
Hi DKirwan,

Sounds great. As I told you before, your Calendar-Heatmap does a great job, and is a good candidate for being included in ng2 components
