### ISSUE TITLE
fork and publish

### ISSUE THREAD

**Issue by tbaeg** [DKirwan/calendar-heatmap#27]
Hey @DKirwan, 

First wanted to thank you for creating this library! But also I wanted to give you a heads up. I've forked the repo for purposes of just publishing it to `npm`. I've made a few changes; mainly upgrading to the latest `d3` with a few other things I'd like to do (remove `moment` dependency). I plan on migrating the code to a repository called `calendar-heatmap-mini`.

I realize the code is MIT licensed but still felt it was important to let you know. I will of course credit you as a source! If there are any issues, please let me know, thanks!

**Comment by DKirwan** [comment]
Thanks @tbaeg! To be honest I don't have the time to continue development on this so your efforts are welcome and appreciated. I'm just maintaining the code for anybody who currently uses it.

**Comment by tbaeg** [comment]
Going through some issue clean up and saw this was still open. I did as I mentioned above many months ago. Closing issue. Thanks again!

Shameless plug: https://github.com/tbaeg/calendar-heatmap-mini :)
