### ISSUE TITLE
what are the advantages over cal-heatmap?

### ISSUE THREAD

**Issue by polo2ro** [DKirwan/calendar-heatmap#3]
hi,
i just found this other projects in my stared repositories: https://github.com/wa0x6e/cal-heatmap 
is your project different? maybe a focus on simplicity. I just wanted to know your reasons about not using cal-heatmap.
thanks

**Comment by DKirwan** [comment]
Hey Paul! That's a good question. Cal-Heatmap is a really nice project with lots of configuration options. I made this d3 heatmap as an exercise for myself, to go through the challenges associated with it and hopefully make a heatmap that's nice to use that developers can learn from and use in their own apps.

What is on master right now is the MVP. I want to build on this with a focus on keeping it lightweight and easy to use for developers and site visitors alike. Right now Cal-heatmap is better for production cases as it has unit tests and is more 'battle tested'. I'll be adding unit tests to this as the project matures and hopefully then it can offer an alternative to cal-heatmap (albeit for simpler use cases) in the future.

**Comment by polo2ro** [comment]
thanks for the quick reply, always cool to have alternatives!
