### ISSUE TITLE
Making countForDate fast

### ISSUE THREAD

**Issue by zookzook** [DKirwan/calendar-heatmap#36]
Currently the `countForDate` function searches the complete data set in the worst-case:

```
        function countForDate(d) {
            var count = 0;
            var match = chart.data().find(function (element, index) {
                return moment(element.date).isSame(d, 'day');
            });
            if (match) {
                count = match.count;
            }
            return count;
        }
```

This function has a worst-case complexity of O(n\*n). For 365 values my computer takes 2 seconds for rendering, because of 365*365 = 133225 (worst-case) calling `moment(element.date).isSame(d, 'day');`

It is possible to use a simple map for getting the count values. First the map is calculated when the data setter is called. As key we use the time format 'YYYY-MM-DD':

```
chart.data = function (value) {
        if (!arguments.length) { return data; }
        data = value;

        counterMap= {};

        data.forEach(function (element, index) {
            var key= moment(element.date).format( 'YYYY-MM-DD' );
            var counter= counterMap[key] || 0;
            counterMap[key]= counter + element.count;
        });

        return chart;
    };
```
So, the complexity for the new data setter is O(n) and that's ok.

Now the countForDate function can be reduced to this:

```
        function countForDate(d) {
            var key= moment(d).format( 'YYYY-MM-DD' );
            return counterMap[key] || 0;
        }

```
and the complexity is O(1)!

After that the rendering takes only 120 ms!

**Comment by DKirwan** [comment]
Good job! Can you create a PR with these changes that we can review?

**Comment by zookzook** [comment]
PR is there: https://github.com/DKirwan/calendar-heatmap/pull/37

**Comment by DKirwan** [comment]
Merged. Thank you.
