### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by GowthamGr** [DKirwan/calendar-heatmap#41]
Hi Darragh ,
I dont know how to use heatmap in react native android and ios.Can you please help me to solve this.If i any related link that may be useful for me.Thanks in advance.

**Comment by DKirwan** [comment]
This would be tricky to do, since there isn't a DOM in react native. IT would be possible in react, but not easily in react native.

If you really want to explore this option, check out https://hswolff.com/blog/react-native-art-and-d3/ to see if that will help.

**Comment by GowthamGr** [comment]
Thank you Darragh.

**Comment by GowthamGr** [comment]
In ionic can we able to achieve this.
